
services:
  db:
    image: postgres:15
    container_name: bolsy-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: martin1707
      POSTGRES_DB: bolsy_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: bolsy-backend
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=martin1707
      - DB_NAME=bolsy_db
      - DB_PORT=5432
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: bolsy-frontend
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

      
volumes:
  pgdata: