#Usa imagen oficial de Node.js
FROM node:20

#Crea y usa el directorio de trabajo
WORKDIR /app

#Copia archivos de dependencias
COPY package*.json ./

#Instala dependencias
RUN npm install

#Copia el resto del codigo
COPY . .

#Expone el puerto de express
EXPOSE 3001

# Comando para iniciar la aplicacion
CMD ["npm","start"]
