# Usa imagen oficial de Node.js
FROM node:20

# Crea y usa el directorio de trabajo
WORKDIR /app

# Copia archivos de dependencias
COPY package*.json ./

# Instala dependencias
RUN npm install

# Copia el resto del código
COPY . .

# Genera el cliente de Prisma con los binarios correctos
RUN npx prisma generate

# Expone el puerto de Express
EXPOSE 3001

# Comando para iniciar la aplicación
CMD ["node", "index.js"]
